FROM jupyter/scipy-notebook:bb222f49222e
MAINTAINER herman.tolentino@gmail.com

# some housekeeping
USER root

ENV DEBIAN_FRONTEND noninteractive

RUN ln -sf /bin/bash /bin/sh && \
    mkdir -p /srv/scripts && \
    mkdir -p /srv/nbgrader/exchange && \
    chown -R $NB_USER /srv/nbgrader/exchange && \
    ln -s /bin/tar /bin/gtar

# install jupyterlab, jupyter_client
RUN conda install -c conda-forge jupyterlab ipywidgets && \
    conda install jupyter_client && \
    jupyter serverextension enable --py jupyterlab --sys-prefix

RUN conda update notebook jupyterhub jupyterlab

RUN apt-get update && \
    apt-get install -y libpq-dev libssl-dev libsasl2-dev libssh2-1-dev \
      libmariadb-client-lgpl-dev mongodb-clients poppler-utils nano \
      postgresql-client sqlite3 mariadb-client python-mysqldb gdal-bin gfortran

RUN echo "jovyan ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
#RUN echo "jovyan:geeks@moph11000" | chpasswd && \
#    usermod -aG sudo jovyan && \
RUN chmod a+w -R /opt/conda && \
    conda install conda-build && \
    conda clean -tipsy

# Python Geoserver API
RUN source activate /opt/conda/envs/python2 && \
    cd /tmp && \
    git clone https://github.com/boundlessgeo/gsconfig.git && \
    cd gsconfig && \
    python setup.py install && \
    cd .. && \
    python -m geoserver.catalog && \
    rm -fvR gsconfig && \
    cd /home/jovyan/work && \
    source deactivate

RUN mkdir -p /home/jovyan/work/notebooks && \
    mkdir -p /home/jovyan/work/shared && \
    mkdir -p /home/jovyan/work/modules && \
    mkdir -p /home/jovyan/work/geoserver && \
    mkdir -p /home/jovyan/.local/share

COPY ./permissions.sh /srv/permissions.sh
COPY ./notebooks/HelloWorld.ipynb /home/jovyan/work/
COPY ./notebooks/Shared-Notebook.ipynb /home/jovyan/work/shared/
COPY ./modules/*.sh /home/jovyan/work/modules/

RUN chmod a+w -R /home/jovyan/work/shared && \
    chmod a+w -R /home/jovyan/work/modules && \
    chmod a+w -R /home/jovyan/work/geoserver && \
    chmod a+w -R /home/jovyan/work/notebooks && \
    chmod a+w -R /home/jovyan/.local/

RUN chown -R jovyan:users /home/jovyan/work/shared && \
    chown -R jovyan:users /home/jovyan/work/modules && \
    chown -R jovyan:users /home/jovyan/work/geoserver && \
    chown -R jovyan:users /home/jovyan/work/notebooks

USER jovyan

WORKDIR /home/jovyan/work
#VOLUME ['/home/jovyan/work/modules', '/home/jovyan/work/shared', '/home/jovyan/work/geoserver']
